name: node-gyp integration
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  node-gyp-integration:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: ["3.10", "3.12", "3.14"]
        include:
          - os: macos-15-intel  # macOS on Intel
            python-version: "3.14"
          - os: ubuntu-24.04-arm  # Ubuntu on ARM
            python-version: "3.14"
          - os: windows-11-arm  # Windows on ARM
            python-version: "3.14"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Clone gyp-next
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          path: gyp-next
          persist-credentials: false
      - name: Clone nodejs/node-gyp
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          repository: nodejs/node-gyp
          path: node-gyp
          persist-credentials: false
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: "lts/*"
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true
      - name: Install Python dependencies
        run: |
          cd gyp-next
          python -m pip install --upgrade pip
          pip install --editable .
          pip uninstall -y gyp-next
      - name: Install Node.js dependencies
        run: |
          cd node-gyp
          npm install --no-progress
      - name: Replace gyp in node-gyp
        shell: bash
        run: |
          rm -rf node-gyp/gyp
          cp -r gyp-next node-gyp/gyp
      - name: Run tests (macOS or Linux)
        if: runner.os != 'Windows'
        run: |
          cd node-gyp
          npm test --python="${pythonLocation}/python"
      - name: Run tests (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          cd node-gyp
          npm run test --python="${env:pythonLocation}\\python.exe"
