# TODO: Enable pytest --doctest-modules

name: Python_tests
on:
  push:
  pull_request:
  workflow_dispatch:
permissions: {}
jobs:
  Python_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Lint with ruff  # See pyproject.toml for settings
        uses: astral-sh/ruff-action@278981a28ce3188b1e39527901f38254bf3aac89 # v4.1.0
      - run: ruff format --check --diff
      - uses: wagoid/commitlint-github-action@b948419dd99f3fd78a6548d48f94e3df7f6bf3ed # v6.2.1

  Python_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: ["3.11", "3.12", "3.13", "3.14", "3.15"]
        include:
          - os: macos-26-intel  # macOS on Intel
            python-version: 3.x
          - os: ubuntu-24.04-arm  # Ubuntu on ARM
            python-version: 3.x
          - os: windows-11-arm  # Windows on ARM
            python-version: 3.x
          - os: windows-2025-vs2026  # Windows with Visual Studio 2026
            python-version: 3.x
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true
      - uses: seanmiddleditch/gha-setup-ninja@3b1f8f94a2f8254bd26914c4ab9474d4f0015f67 # v6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --editable ".[dev]"
      - run: ./gyp -V && ./gyp --version && gyp -V && gyp --version
      - name: Test with pytest  # See pyproject.toml for settings
        run: pytest
      # - name: Run doctests with pytest
      #   run: pytest --doctest-modules
      - name: Test CLI commands on a pipx install
        run: |
          pipx run --no-cache --spec ./ gyp --help
          pipx run --no-cache --spec ./ gyp --version
