# https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

name: visual-studio
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  visual-studio:
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        include:
          - os: windows-2022
            msvs-version: 2022
          - os: windows-2025
            msvs-version: 2026
          - os: windows-11-arm
            msvs-version: 2022  # Fix this when Visual Studio 2025 is released
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Use Python 3
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.x"
      - name: Install Dependencies
        run: npm install
      - name: Run Node tests
        shell: pwsh
        run: npm run test --python="${env:pythonLocation}\\python.exe" --msvs-version="${{ matrix.msvs-version }}"
